# -*- coding: utf-8 -*-
"""Assignment 1 & 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D4Yo_8GH-x5t0EQb3NAPnALwiOCE48Np

Qn 1
"""

x = 2
y = 5
xy = 'Hey'
print (x+y, xy)

"""Qn 2"""

print("""My name is Rajath Kumar M.P.

I love Python.""")

string1 = 'World'
print('Hello', string1)

string2 = '!'
print('Hello', string1, string2)

print('Hello' + string1 + string2)

print("Jan\nFeb\nMar\nApr\nMay\nJun\nJul\nAug")

print("I want \\n to be printed.")

x = 10
print(type(x))
 
s = 'abc'
print(type(s))
 
value= True
print(type(value))

percent=90.00
type(percent)